name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: sonarcloud/sonarcloud-github-action@v1
        with:
          args: >
            -Dsonar.projectKey=jashnow
            -Dsonar.organization=jashnow
            -Dsonar.sources=.
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
