name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=jashnow
            -Dsonar.organization=jashnow
            -Dsonar.sources=.
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
